logicalclocks/logicalclocks.github.io

mkdocs.yml
Reverts logicalclocks/logicalclocks.github.io#4
=> Revert "Error pages loading resources incorrectly, see https://github.com/mkdocs/mkdocs/issues/1598"

docs/user_guides/fs/feature_group/data_types.md
(cherry picked from commit 6a954fd11dc1f98b8dead64e73a382a76c9b9f25)
=> [HOPSWORKS-3242] Data types guide update 

.github/workflows/mkdocs-release.yml
**DO NOT MERGE UNTIL RELEASE IS TO BE MADE.**
=> Release 3.0 documentation

.gitignore, docs/user_guides/fs/feature_view/transformation-function.md, docs/user_guides/integrations/emr/networking.md
* remove old readthedocs links
* add gitignore
(cherry picked from commit 596680e1a217ec973ffb8c6818ca22f5a3bcaaeb)
=> Remove deprecated readthedocs links

docs/setup_installation/common/terraform.md
Fixes https://github.com/logicalclocks/cloud-tickets/issues/80
=> Update terraform examples

docs/setup_installation/gcp/getting_started.md
Fixes https://github.com/logicalclocks/cloud-tickets/issues/84
=> Update GCP prerequisites to include APIs required to be enabled on a project

docs/user_guides/fs/feature_group/create.md, docs/user_guides/fs/feature_group/create_external.md, docs/user_guides/mlops/serving/deployment.md, docs/user_guides/mlops/serving/inference-batcher.md, docs/user_guides/mlops/serving/inference-logger.md, docs/user_guides/mlops/serving/predictor.md, docs/user_guides/mlops/serving/resources.md, docs/user_guides/mlops/serving/transformer.md, docs/user_guides/mlops/vector_database/index.md, docs/user_guides/projects/git/configure_git_provider.md, docs/user_guides/projects/jobs/pyspark_job.md, docs/user_guides/projects/jobs/python_job.md, docs/user_guides/projects/jobs/spark_job.md, docs/user_guides/projects/kafka/consume_messages.md, docs/user_guides/projects/kafka/create_schema.md, docs/user_guides/projects/kafka/create_topic.md, docs/user_guides/projects/kafka/produce_messages.md, docs/user_guides/projects/opensearch/connect.md, docs/user_guides/projects/project/create_project.md, docs/user_guides/projects/secrets/create_secret.md, mkdocs.yml
- add macros for variables
- add comment
- 3.0
=> [FSTORE-11][3.0] Add macros for variables for version in links

2.5/index.html, versions.json
- add 2.5 link
- fix redirect
- fix link
=> Add 2.5 redirect

docs/admin/ldap/configure-server.md, docs/admin/oauth2/create-azure-client.md, docs/admin/oauth2/create-client.md, docs/admin/roleChaining.md, docs/setup_installation/aws/cluster_creation.md, docs/setup_installation/aws/eks_ecr_integration.md, docs/setup_installation/aws/getting_started.md, docs/setup_installation/aws/restrictive_permissions.md, docs/setup_installation/common/adding_removing_workers.md, docs/setup_installation/common/gpu_support.md, docs/setup_installation/common/sso/ldap.md, docs/setup_installation/common/sso/oauth.md, docs/setup_installation/common/terraform.md, docs/setup_installation/gcp/cluster_creation.md, docs/setup_installation/gcp/getting_started.md, docs/user_guides/fs/storage_connector/creation/s3.md, docs/user_guides/migration/30_migration.md, docs/user_guides/projects/git/clone_repo.md
Fixes https://hopsworks.atlassian.net/browse/CLOUD-122
Fixes https://hopsworks.atlassian.net/browse/CLOUD-122
=> fixes for aws geting started and role chaining

docs/setup_installation/gcp/getting_started.md
Fixes https://hopsworks.atlassian.net/browse/CLOUD-64
=> [CLOUD-64] fix typo

docs/setup_installation/aws/instance_profile_permissions.md
https://hopsworks.atlassian.net/browse/CLOUD-33
=> [CLOUD-33] Add ecr:TagResource permission to instance profile

docs/user_guides/fs/feature_group/data_validation.md
Cherry pick fix to documentation from hackathon feedback
=> [FSTORE-426] errors out of date info in the data validation documentation 3.0

docs/user_guides/fs/feature_group/data_validation.md
validation_insertion_policy -> validation_ingestion_policy
=> [FSTORE-431] Fix parameter typo validation_insertion_policy

docs/user_guides/fs/feature_group/data_validation.md
=> [FSTORE-431] fix typo in user guide for data validation 3.0

docs/setup_installation/index.md, docs/user_guides/client_installation/index.md, docs/user_guides/fs/compute_engines.md, docs/user_guides/fs/index.md, docs/user_guides/index.md, docs/user_guides/integrations/emr/emr_configuration.md, docs/user_guides/integrations/index.md, docs/user_guides/integrations/python.md, mkdocs.yml
- [FSTORE-360] Installation Guide Restructuring (#137)
- [FSTORE-360][Append] Small fixes, added pypi link, revised OSX/Windows instructions (#139)
[FSTORE-360]: https://hopsworks.atlassian.net/browse/FSTORE-360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FSTORE-360]: https://hopsworks.atlassian.net/browse/FSTORE-360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [3.0][FSTORE-360] Client installation guide

docs/admin/monitoring/export-metrics.md, mkdocs.yml
https://hopsworks.atlassian.net/browse/HWORKS-244
=> [HWORKS-244] Documentation for exporting Prometheus metrics

mkdocs.yml
(cherry picked from commit 292518126f621f4ca88221ffde34cef981ea924e)
=> [FSTORE-360][Append2] Moved client installation guide 

docs/setup_installation/aws/instance_profile_permissions.md
https://hopsworks.atlassian.net/browse/CLOUD-28
=> [CLOUD-28] Publish internal services images to ECR/ACR

docs/setup_installation/aws/restrictive_permissions.md
https://hopsworks.atlassian.net/browse/CLOUD-210
=> [CLOUD-210] Fixes for restrictive permissions

docs/setup_installation/aws/aws_permissions.json, docs/setup_installation/aws/restrictive_permissions.md
https://hopsworks.atlassian.net/browse/CLOUD-209
=> [CLOUD-209] Add default aws permissions needed by managed.hopsworks.ai

docs/setup_installation/aws/getting_started.md
Fixes https://hopsworks.atlassian.net/browse/CLOUD-350
=> [CLOUD-350] stop offering access key as a way to connect to AWS

docs/setup_installation/gcp/getting_started.md
Fixes https://hopsworks.atlassian.net/browse/CLOUD-315
=> [CLOUD-315] add prerequisit user permissions for gcp

docs/setup_installation/gcp/gcp_permissions.yml, docs/setup_installation/gcp/restrictive_permissions.md
Fixes https://hopsworks.atlassian.net/browse/CLOUD-358
=> [CLOUD-358] Add default GCP permissions

docs/setup_installation/on_prem/hopsworks_installer.md
https://hopsworks.atlassian.net/browse/CLOUD-383
=> [CLOUD-383] Change installer version

docs/setup_installation/aws/getting_started.md, docs/setup_installation/aws/restrictive_permissions.md, docs/setup_installation/azure/getting_started.md, docs/setup_installation/gcp/getting_started.md
Fixes https://hopsworks.atlassian.net/browse/CLOUD-382
=> [CLOUD-382] add note about VPC endpoint

docs/setup_installation/aws/instance_profile_permissions.md, docs/setup_installation/aws/upgrade_3.0.md
Fixes https://hopsworks.atlassian.net/browse/CLOUD-396
=> [CLOUD-396] remove unused permission from asw instance profile policy

docs/setup_installation/aws/instance_profile_permissions.md, docs/setup_installation/aws/upgrade_3.0.md
=> Cloud 360 3.1

docs/setup_installation/aws/aws_permissions.json
Fixes https://hopsworks.atlassian.net/browse/CLOUD-415
=> [CLOUD-415] put some structure in the AWS cross accout permissions

docs/index.md, mkdocs.yml
* Add slack channel to docs landing page
* Add slack to bottom bar
=> [HWORKS-423] Public slack channel 3.1

docs/index.md, mkdocs.yml
* Add slack channel to docs landing page
* Add slack to bottom bar
=> [HWORKS-423] Public slack channel 3.0

docs/setup_installation/common/terraform.md
Fixes https://hopsworks.atlassian.net/browse/CLOUD-423
Fixes https://hopsworks.atlassian.net/browse/CLOUD-424
=> [CLOUD-423][CLOUD-424] Fix terraform example and use azure terminology

docs/setup_installation/common/terraform.md
Fixes https://hopsworks.atlassian.net/browse/CLOUD-480
=> [CLOUD-480] Update terraform helpers modules

docs/setup_installation/azure/aks_acr_integration.md
Fixes https://hopsworks.atlassian.net/browse/CLOUD-420
=> [CLOUD-420] fix documentation for AKS

docs/setup_installation/azure/azure_permissions.json, docs/setup_installation/azure/restrictive_permissions.md
Fixes https://hopsworks.atlassian.net/browse/CLOUD-447
=> [CLOUD-447] add permission to check azure managed id

docs/setup_installation/aws/restrictive_permissions.md
Fixes https://hopsworks.atlassian.net/browse/CLOUD-607
=> [CLOUD-607] append - fix link

docs/index.md
=> Update slack link

docs/index.md
=> Update slack link (#314)

docs/setup_installation/common/terraform.md
Fixes https://hopsworks.atlassian.net/browse/CLOUD-684
=> [CLOUD-684] Update terraform examples

docs/setup_installation/common/terraform.md
Fixes https://hopsworks.atlassian.net/browse/CLOUD-700
=> [CLOUD-700] Add GCP terraform example

docs/user_guides/fs/feature_view/feature-vectors.md
* enhance feature-vectors.md
* address comment
* make python and java code consistent
=> [FSTORE-1269] Extend get_feature_vector in user guide (#353)

docs/user_guides/projects/jobs/pyspark_job.md, docs/user_guides/projects/jobs/python_job.md, docs/user_guides/projects/jobs/schedule_job.md, docs/user_guides/projects/jobs/spark_job.md
* Add short info about scheduling in Jobs guide
* Apply suggestions from code review
---------
=> Add short info about scheduling in Jobs guide (#381)

docs/user_guides/projects/jobs/pyspark_job.md, docs/user_guides/projects/jobs/python_job.md, docs/user_guides/projects/jobs/schedule_job.md, docs/user_guides/projects/jobs/spark_job.md
* Add short info about scheduling in Jobs guide
* Apply suggestions from code review
---------
=> Cherry-pick Job scheduling hint

mkdocs.yml
=> Fix fs api link in API dropdown.

docs/user_guides/projects/jobs/ray_job.md, docs/user_guides/projects/jupyter/ray_notebook.md
* [HWORKS-2193] Update project mount dir for Ray
* Extra changes
[HWORKS-2193]: https://hopsworks.atlassian.net/browse/HWORKS-2193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [HWORKS-2193] Update project mount dir for Ray (#476)

docs/user_guides/projects/jobs/notebook_job.md, docs/user_guides/projects/jobs/pyspark_job.md, docs/user_guides/projects/jobs/python_job.md, docs/user_guides/projects/jobs/spark_job.md
This PR cherry-pick changes done by PR: https://github.com/logicalclocks/logicalclocks.github.io/pull/478
=> [HWORKS-2190][4.3][APPEND] Updating job configuration to include file, pyfiles, archives and jars

.github/workflows/mkdocs-release.yml, docs/user_guides/projects/jobs/notebook_job.md, docs/user_guides/projects/jobs/pyspark_job.md, docs/user_guides/projects/jobs/python_job.md, docs/user_guides/projects/jobs/ray_job.md, docs/user_guides/projects/jobs/spark_job.md
=> [HWORKS-2322] Add defaultArgs field to job docs and clarify nested fields
